name : GitHub Actions Secret
env :
    MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
    MYSQL_USER: ${{ secrets.MYSQL_USER }}
    MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    MYSQL_DB: ${{ secrets.MYSQL_DB }}